@startuml
:Usuario:
:Administrador:
usecase "Inicio sesion" as UC1
usecase "Recuperar contraseña" as UC2
usecase "Modificar contraseña" as UC3
usecase "Cerrar sesion" as UC4
usecase "Registrar usuario" as UC5
usecase "Instalar programa" as UC6
Usuario -- UC1
Usuario -- UC2
Usuario -- UC3
Usuario --UC4
Usuario <|-- Administrador
Administrador -- UC5
Administrador -- UC6
@enduml