@startuml
:Ciudadano:
:Ciudadano extranero: as CiuEx
usecase "Registrar entrada" as UC1
usecase "Tomar huellas" as UC2
Ciudadano <|-- CiuEx
Ciudadano -- UC1
CiuEx -- UC2
UC1 <.. UC2 : <<extend>
@enduml